<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: Florian Humer
 * Date: Tue, 29 May 2018 10:53:40 +0000
 */

$conf['title'] = '$HABIDAT_TITLE';
$conf['lang'] = 'de';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-sa';
$conf['basedir'] = '/';
$conf['useacl'] = 1;
$conf['authtype'] = 'authldap';
$conf['superuser'] = 'admin';
$conf['disableactions'] = 'register';
$conf['target']['extern'] = '_blank';
$conf['userewrite'] = '2';
$conf['useslash'] = 1;
$conf['plugin']['bootswrapper']['loadBootstrap'] = 1;
$conf['plugin']['authldap']['server'] = '$HABIDAT_DOCKER_PREFIX-ldap';
$conf['plugin']['authldap']['usertree'] = 'ou=users,$HABIDAT_LDAP_BASE';
$conf['plugin']['authldap']['grouptree'] = 'ou=groups,$HABIDAT_LDAP_BASE';
$conf['plugin']['authldap']['userfilter'] = '(|(&(cn=%{user})(objectClass=inetOrgPerson))(&(mail=%{user})(objectClass=inetOrgPerson))(&(uid=%{user})(objectClass=inetOrgPerson)))';
$conf['plugin']['authldap']['groupfilter'] = '(&(member=%{dn})(objectClass=groupOfNames))';
$conf['plugin']['authldap']['version'] = 3;
$conf['plugin']['authldap']['binddn'] = 'cn=admin,$HABIDAT_LDAP_BASE';
$conf['plugin']['authldap']['bindpw'] = '$HABIDAT_LDAP_ADMIN_PASSWORD';
$conf['plugin']['authldap']['userkey'] = 'cn';
$conf['plugin']['authldap']['mapping']['name'] = 'displayname';

// end auto-generated content
