---

discourse_connect_url: https://$HABIDAT_NEXTCLOUD_SUBDOMAIN.$HABIDAT_DOMAIN/index.php/apps/discoursesso
discourse_connect_secret: $HABIDAT_DISCOURSE_SSO_SECRET
enable_discourse_connect: 'true'
logout_redirect: $HABIDAT_PROTOCOL://$HABIDAT_NEXTCLOUD_SUBDOMAIN.$HABIDAT_DOMAIN/index.php/apps/discoursesso/logout
