version: '3'

services:

  habidat:
    image: habidat/setup
    volumes:
      - ./habidat:/habidat/store 
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./setup-docker.env  
