---
default_locale: de
title: habi*DAT
site_description: habi*DAT Test Plattform fuer Hausprojekte
contact_email: support@xaok.org
contact_url: habidat-staging
notification_email: info-no-reply@discourse.habidat-staging
site_contact_username: admin
logo_url: "/images/d-logo-sketch.png"
logo_small_url: "/images/d-logo-sketch-small.png"
company_short_name: habiDAT
company_full_name: habiDAT
company_domain: habidat-staging
top_menu: latest|categories|new|unread|top
share_links: email
desktop_category_page_style: categories_and_latest_topics
category_colors: BF1E2E|F1592A|F7941D|9EB83B|3AB54A|12A89D|25AAE2|0E76BD|652D90|92278F|ED207B|8C6238|231F20|808281|B3B5B4|283890
category_style: bullet
push_notifications_prompt: 'true'
invite_only: 'false'
login_required: 'true'
enable_sso: 'true'
sso_allows_all_return_paths: 'true'
sso_url: https://cloud.habidat-staging/index.php/apps/discoursesso
sso_secret: 2134upiohasdf0dsf01ks89274309h
sso_overrides_groups: 'true'
sso_overrides_email: 'true'
sso_overrides_name: 'true'
email_editable: 'false'
logout_redirect: https://cloud.habidat-staging/index.php/apps/discoursesso/logout
default_trust_level: '2'
allow_flagging_staff: 'true'
force_https: 'false'
ldap_enabled: 'true'
ldap_user_create_mode: auto
ldap_hostname: ldap
ldap_port: '389'
ldap_method: plain
ldap_base: dc=habidat-staging
ldap_uid: cn
ldap_bind_dn: cn=ldap-read, dc=habidat-staging
ldap_password: dDD2TNM6kHuUeC4n
ldap_filter: ''
