version: '3.5'

volumes: 
  db:
  config:
  files:
  upload:
  images:

networks:
  $HABIDAT_DOCKER_PREFIX-proxy:
    external:
      name: $HABIDAT_PROXY_NETWORK
  $HABIDAT_DOCKER_PREFIX-back:
    external:
      name: $HABIDAT_BACKEND_NETWORK

services:
  db:
    image: mariadb
    container_name: $HABIDAT_DOCKER_PREFIX-direktkredit-db    
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./db.env    
    networks:
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m

  web:
    image: habidat/direktkredit
    restart: unless-stopped
    container_name: $HABIDAT_DOCKER_PREFIX-direktkredit  
    env_file:
      - ./web.env   
    volumes:
      - config:/habidat/config
#      - direktkredit-templates:/habidat/templates
      - files:/habidat/public/files
      - images:/habidat/public/images
      - upload:/habidat/upload      
    depends_on:
      - db
    ports:
      - 8020
    networks:
      - $HABIDAT_DOCKER_PREFIX-proxy
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m
