version: '3.5'

volumes: 
  ldap-data:
  ldap-config:
  sso-config:

networks:
  $HABIDAT_DOCKER_PREFIX-proxy:
    external:
      name: $HABIDAT_DOCKER_PREFIX-proxy
  $HABIDAT_DOCKER_PREFIX-back:
    driver: bridge  
    name: $HABIDAT_DOCKER_PREFIX-back


services:  

  ldap:
    image: osixia/openldap:1.2.3
    restart: unless-stopped
    container_name: $HABIDAT_DOCKER_PREFIX-ldap
    env_file:
      - ./ldap.env    
    ports:
      - 389
    volumes:
      - ldap-data:/var/lib/ldap/
      - ldap-config:/etc/ldap/slap.d/
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service --loglevel debug
    networks:
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m  

#  sso:
#    build: 
#      context: "https://github.com/LemonLDAPNG/lemonldap-ng-docker.git"
#    container_name: $HABIDAT_DOCKER_PREFIX-sso      
#    restart: unless-stopped
#    env_file:
#      - ./sso.env
#    volumes:
#      - ./sso-config:/var/lib/lemonldap-ng/conf
#    ports:
#      - 80
#    extra_hosts:
#      - "reload.$HABIDAT_DOMAIN:127.0.0.1"   
#    networks:
#      - $HABIDAT_DOCKER_PREFIX-proxy
#      - $HABIDAT_DOCKER_PREFIX-back
#    logging:
#      options:
#        max-size: 50m

#  sso:
#    build:
#      context: ../../../habidat-sso
#    restart: unless-stopped
#    container_name: $HABIDAT_DOCKER_PREFIX-sso
#    env_file:
#      - ./sso.env
#    volumes:
#      - ./sso.yml:/params.yml
#      - ./cert:/srv/simplesaml/cert
#    networks:
#      - $HABIDAT_DOCKER_PREFIX-proxy
#      - $HABIDAT_DOCKER_PREFIX-back
#    logging:
#      options:
#        max-size: 50m        

  user:
    image: habidat/user:1.0.0 
    restart: unless-stopped
    container_name: $HABIDAT_DOCKER_PREFIX-user
    env_file:
      - ./user.env
#    volumes:
#      - ../store/auth/user-config.json:/habidat-user/config/config.json
    ports:
      - 8090
    #command: node app.js
    #entrypoint: ""
    networks:
      - $HABIDAT_DOCKER_PREFIX-proxy
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m        