version: '3.5'

volumes: 
  ldap-data:
  ldap-config:
  user-data:
$HABIDAT_SSO_DISABLE  sso-config:

networks:
  $HABIDAT_DOCKER_PREFIX-proxy:
    external:
      name: $HABIDAT_PROXY_NETWORK
$HABIDAT_INTERNAL_NETWORK_DISABLE  $HABIDAT_DOCKER_PREFIX-back:
$HABIDAT_INTERNAL_NETWORK_DISABLE    driver: bridge  
$HABIDAT_INTERNAL_NETWORK_DISABLE    name: $HABIDAT_BACKEND_NETWORK
$HABIDAT_EXTERNAL_NETWORK_DISABLE  $HABIDAT_DOCKER_PREFIX-back:
$HABIDAT_EXTERNAL_NETWORK_DISABLE    external: 
$HABIDAT_EXTERNAL_NETWORK_DISABLE      name: $HABIDAT_BACKEND_NETWORK


services:  

  ldap:
    image: osixia/openldap:1.3.0
    restart: unless-stopped
    container_name: $HABIDAT_DOCKER_PREFIX-ldap
    env_file:
      - ./ldap.env    
    ports:
      - 389
    volumes:
      - ldap-data:/var/lib/ldap/
      - ldap-config:/etc/ldap/slapd.d/
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ./memberOf.ldif:/container/service/slapd/assets/config/bootstrap/ldif/03-memberOf.ldif 
    command: --copy-service --loglevel debug
    networks:
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m  

$HABIDAT_SSO_DISABLE  sso:
$HABIDAT_SSO_DISABLE    image: habidat/sso
#    build:
#      context: ../../../habidat-sso
$HABIDAT_SSO_DISABLE    restart: unless-stopped
$HABIDAT_SSO_DISABLE    container_name: $HABIDAT_DOCKER_PREFIX-sso
$HABIDAT_SSO_DISABLE    env_file:
$HABIDAT_SSO_DISABLE      - ./sso.env
$HABIDAT_SSO_DISABLE    volumes:
$HABIDAT_SSO_DISABLE      - ./sso.yml:/params.yml
$HABIDAT_SSO_DISABLE      - ./cert:/var/simplesaml/cert
$HABIDAT_SSO_DISABLE    networks:
$HABIDAT_SSO_DISABLE      - $HABIDAT_DOCKER_PREFIX-proxy
$HABIDAT_SSO_DISABLE      - $HABIDAT_DOCKER_PREFIX-back
$HABIDAT_SSO_DISABLE    logging:
$HABIDAT_SSO_DISABLE      options:
$HABIDAT_SSO_DISABLE        max-size: 50m        

  user:
    image: habidat/user
#    build:
#      context: ../../../habidat-user/habidat-user
    restart: unless-stopped
    container_name: $HABIDAT_DOCKER_PREFIX-user
    env_file:
      - ./user.env
    volumes:
      - user-data:/habidat-user/data
    ports:
      - 8090
    #command: node app.js
    #entrypoint: ""
    networks:
      - $HABIDAT_DOCKER_PREFIX-proxy
      - $HABIDAT_DOCKER_PREFIX-back
    logging:
      options:
        max-size: 50m        
